# server
host: 127.0.0.1
port: 3000


# the directory that contains to build code for testing env or production env.
# default directory name is 'dist'.
buildDir: dist

# Point to static resource path, such as access to images, fonts, etc.
# ref: https://webpack.js.org/configuration/output/
# https://cdn.example.com/assets/', // CDN (always HTTPS)
# publicPath: '//cdn.example.com/assets/', // CDN (same protocol)
# publicPath: '/assets/', // server-relative
publicPath: /

entry:
  app:
    path: index.js
    favicon: images/favicon.ico
    title: normal smart application

# https://webpack.js.org/configuration/devtool/
devtool: eval-source-map

# # Object <key: []>
vendors:

base64Limit: 8192

# Array <string[]>
# right -> node_modules/xxx/xx.js
# error => /node_modules/xxx/xx.js
loaderIncludes:

resolveAlias:
  pages: pages
  assets: assets

globals:
  API_HTTPS:
    start: //
    test: //
    staging: //
    release: //

  API_HTTP:
    start: //
    test:  //
    staging:  //
    release: //

structure:
  # development directory
  src:
  pages:
  assets:

