# server
host: 127.0.0.1
port: 4001


# the directory that contains to build code for testing env or production env.
# default directory name is 'dist'.
buildDir: dist

# Point to static resource path, such as access to images, fonts, etc.
# ref: https://webpack.js.org/configuration/output/
# https://cdn.example.com/assets/', // CDN (always HTTPS)
# publicPath: '//cdn.example.com/assets/', // CDN (same protocol)
# publicPath: '/assets/', // server-relative
publicPath: /

entry:
  app:
    path: index
    favicon: images/favicon.ico
    title: smart react application

devtool: eval-source-map

# @Object {key: <module-name>[]}
# @Array module-name[]
vendors:
  react-vendor:
    - react
    - '@hot-loader/react-dom'
    - react-redux
    - redux-saga
    - '@reduxjs/toolkit'
    - react-router-dom
    - reselect

base64Limit: 8192

# Array <string[]>
# right -> node_modules/xxx/xx.js
# error => /node_modules/xxx/xx.js
loaderIncludes:

# Object { [key]: { start, test, staging, release } }
# [start] for development evn
# [test] for testing env
# [staging] for staging env
# [release] production env
# @@ the value can be contains 'http', also not.
# example: start: yourdomain.com or http://yourdomain.com

mode:
  API_HTTP:
<<<<<<< HEAD
    start: //
    test:  //
    staging:  //
    release: //
=======
    start:
    test:
    staging:
    release:
#    ...custom define if needed
#    example add API_HTTPS and CDN_PATH
#  API_HTTPS:
#    start:
#    ...modeType
#  CDN_PATH:
#    start:
#    ...modeType
>>>>>>> 8177936d0447d205518ef79b77c9757f8e72c141
